---
output:
  bookdown::word_document2:
    reference_docx: Template.docx
    fig_caption: yes
    toc: no
    number_sections: no
    df_print: kable
editor_options: 
  chunk_output_type: inline
bibliography: references.bib
link-citations: true
urlcolor: blue
linkcolor: blue
citationcolor: blue
csl: "`r here:::here('ecology.csl')`"
---

```{r setup, include=FALSE}
set.seed(513)
options(repos = c(CRAN = "http://cran.rstudio.com"))
options(timeout=60*30) #timeout downloads that last longer than 30 minutes

knitr::opts_chunk$set(
  echo = FALSE,
	message = FALSE,
	warning = FALSE,
	progress = FALSE,
	cache = FALSE,
	dpi = 300,
  fig.align = 'center'
)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  knitr, # markdown documents
  flextable, # plot tables
  bookdown, # figure numbering in markdown
  here, # easy file structure
  tidyverse, # data manipulation
  readxl, # read excel files
  ggplot2, # figures
  patchwork, # multiple figures
  sf, # spatial data
  terra, # raster data (new pkg)
  prism, # prism data
  parallel # parallel processing
) 
terraOptions(progress=0) # suppress all progress bars in terra
cores <- parallel::detectCores() # Set number of cores for parallel processing

# Set custom plotting theme
theme_new <- function(base_size = 9,base_family = "Helvetica"){
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.line.x = element_line(color="black", linewidth = 0.25),
      axis.line.y = element_line(color="black", linewidth = 0.25),
      axis.title = element_text(size = 9),
      axis.text = element_text(colour="black", size=8),
      legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      plot.background = element_rect(fill = NA, colour = NA),
      panel.border = element_rect(fill = NA, colour = NA),
      panel.background = element_rect(fill = "white", colour = "black"), 
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(size = 9)
      
    )
}
theme_set(theme_new())

set_flextable_defaults(
  font.family="Times", 
  font.size=12,
  line_spacing=1,
  padding.bottom=1,
  padding.top=1,
  text.align='center')
```

# Overview

# Methods

## Study area

## Field methods

### Phenology information

Leaf color change

Early color change

50% Color change

All leaves changed color

Leaf dropping

Early dropping:

50% leaf drop

All leaves dropped

Tree size

Data preparation

```{r}
# read excel file  
```
