---
output:
  bookdown::word_document2:
    reference_docx: Template.docx
    fig_caption: yes
    toc: no
    number_sections: no
    df_print: kable
editor_options: 
  chunk_output_type: inline
bibliography: references.bib
link-citations: true
urlcolor: blue
linkcolor: blue
citationcolor: blue
csl: "`r here:::here('ecology.csl')`"
---

```{r setup, include=FALSE}
set.seed(513)
options(repos = c(CRAN = "http://cran.rstudio.com"))
options(timeout=60*30) #timeout downloads that last longer than 30 minutes

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  knitr, # markdown documents
  flextable, # plot tables
  bookdown, # figure numbering in markdown
  here, # easy file structure
  tidyverse, # data manipulation
  ggplot2, # figures
  patchwork, # multiple figures
  sf, # spatial data
  terra, # raster data (new pkg)
  prism, # prism data
  parallel # parallel processing
) 
terraOptions(progress=0) # suppress all progress bars in terra
cores <- parallel::detectCores() # Set number of cores for parallel processing

# Set custom plotting theme
theme_new <- function(base_size = 9,base_family = "Helvetica"){
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.line.x = element_line(color="black", linewidth = 0.25),
      axis.line.y = element_line(color="black", linewidth = 0.25),
      axis.title = element_text(size = 9),
      axis.text = element_text(colour="black", size=8),
      legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      plot.background = element_rect(fill = NA, colour = NA),
      panel.border = element_rect(fill = NA, colour = NA),
      panel.background = element_rect(fill = "white", colour = "black"), 
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(size = 9)
      
    )
}
theme_set(theme_new())

set_flextable_defaults(
  font.family="Times", 
  font.size=12,
  line_spacing=1,
  padding.bottom=1,
  padding.top=1,
  text.align='center')

# Set directory structure for project
dir.create(here("Data"), showWarnings = FALSE)
dir.create(here("Data", "Spatial"), showWarnings = FALSE)
```

# Overview

# Data

## Budburst

## PRISM

To characterize the study area's climate, we obtained monthly precipitation totals, minimum temperatures, and maximum temperature 30-year normals from PRISM [@prismclimategroup2021Monthly30yearClimate] using the *prism* package [@prism].

```{r DL_PRISM}
dir.create(here("Data", "Spatial", "PRISM"), showWarnings = FALSE) # Create directory to hold data
prism_set_dl_dir(here("Data", "Spatial", "PRISM")) # tell program to download PRISM data to the directory we just created
  
# download climate normals
get_prism_normals("ppt", "800m", annual = TRUE, keepZip = FALSE) # annual precipitation
get_prism_normals("tmin", "800m", mon=1, keepZip = FALSE) # minimum temperature in January
get_prism_normals("tmax", "800m", mon=7, keepZip = FALSE) # maximum temperature in July


```

# Data preparation

```{r}
# read in budburst observation csv file
budburst <- read.csv(here("Data", "budburst_observations_1733415315.csv")) %>%
  filter(genus=="Populus" & species=="tremuloides") %>% 
  filter(administrative_area_level_1 %in% c("CO", "Colorado")) %>%  # limit to sites in Colorado
  filter(phenophase_plant_structure %in% c("Autumn Leaf Color Change", "Autumn Leaves Dropping")) # limit dataset to just fall phenophase data

budburst.sf <- st_as_sf(x = budburst, coords = c("longitude", "latitude"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# read in prism data
prism_set_dl_dir(here("Data", "Spatial", "PRISM")) # tell computer where PRISM data is stored
ppt.normal <- prism_archive_subset("ppt", "annual normals", resolution="800m") %>% # set what PRISM data we want to look at
  pd_to_file() %>% # get path
  rast() # read in data 

# overlay budburst observations and extract precipitation normals
budburst.sf <- extract(ppt.normal,budburst.sf, bind=T)

```

# Analyses

```{r}
budburst <- budburst.sf %>%  as.data.frame() %>% filter(phenophase_title=="50% Color change") %>% 
  # convert observation_date to date object 
  mutate(date=as.Date(observation_date, format="%m/%d/%Y")) %>% 
  mutate(year =lubridate::year(date), doy=lubridate::yday(date))

ggplot(budburst, aes(y=doy, x=PRISM_ppt_30yr_normal_800mM4_annual_bil))+geom_point()+geom_smooth(method="lm")

```

# References

::: {#refs}
:::
